<?php
/** @var Amasty\BaharOleg\Block\Form $block */
$cssClass = $block->getData('css_class_form');
$qtyValue = $block->getQtyValue();
?>

<div>
    <form action="<?= $block->getFormAction() ?>" method="POST" data-mage-init='{"validation": {}}'>
        <h3>Sku</h3>
        <div data-bind="scope: 'searchAutocomplete'">
            <!-- ko template: getTemplate() -->
            <!-- /ko -->
        </div>
        <h3>Qty</h3>
        <?= $block->isShowQtyField() ? ("<input class = \"$cssClass\" value = $qtyValue type=\"number\" name=\"qty\" 
data-validate='{ \"integer\": true, \"required\": true, \"validate-greater-than-zero\": true}'>") : "" ?>
        <?= $block->getChildHtml(); ?>
        <button class="<?=$cssClass?>" type="submit">submit</button>
    </form>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "searchAutocomplete": {
                        "component": "Amasty_BaharOleg/js/koAutocomplete",
                        "template": "Amasty_BaharOleg/koAutocomplete"
                    }
                }
            }
        }
    }
</script>
